version: "3"
services:
  postgres:
    image: postgres:11.2-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"

volumes:
  pgdata:
    driver: local
